name: Automating Azure Cloud Storage deployment

on:
  push:
    branches: [ master ]  

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Infrastructure
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh TechCrush mytccapstone testcontainer
          
      - name: Test Management Tool & Log
        run: |
          chmod +x ./manage_storage_account.sh
          # Running a 'list' command to prove the connection works...
          ./manage_storage_account.sh list
          # Uploading a dummy file to verify the 'upload'  logic
          echo "GitHub Actions Test File" > download_file1.txt
          ./manage_storage_account.sh upload download_file1.txt mytccapstone testcontainer
        
      - name: Archive Production Logs
        uses: actions/upload-artifact@v4
        with:
          name: deployment-activity-log
          path: activity_log.txt
          retention-days: 7